
import React, { useMemo, useState } from 'react';
import { PixelButton } from '../components/PixelComponents.tsx';
import { MOTION_TYPES } from '../constants.ts';

interface LandingPageProps {
  onGetStarted: () => void;
  onViewDocs: () => void;
}

const CDN_BASE = "https://cdn.rika-ai.com/assets/frontpage/";
const GIF_BASE = `${CDN_BASE}gifs/`;
const EXAMPLES_BASE = `${CDN_BASE}examples/`;

const MOTION_PROMPTS: Record<string, string> = {
  idle: 'side-view, 2D game character standing in place, breathing motion, body sways up-and-down slightly.',
  attack: 'side-view, 2D game character raises weapon to perform a powerful strike forward.',
  walk: 'side-view, 2D game character walks forward.',
  hit: 'side-view, 2D game character getting hit and knocked backward.',
  defeated: 'side-view 2D game character getting hit, kneel down and fall to the ground.'
};

const DISPLAY_GIFS = Array.from({ length: 14 }, (_, i) => `${GIF_BASE}${i + 1}.gif`);
const FALLBACK_IMAGE = `${GIF_BASE}1.gif`;

const FAQS = [
  {
    q: "Do I need to use my own pixel character to generate animations?",
    a: "Yes, you need to prepare your own pixel character. You can upload PNG images with either solid or transparent backgrounds. Currently, Rika AI supports 64x64 and 128x128 pixel art. You can select the pixel scale in the generation parameters."
  },
  {
    q: "Are the generated animations pixel-perfect?",
    a: "Yes, the animations generated by Rika AI are guaranteed to be pixel-perfect, with no blurred pixels or anti-aliasing artifacts."
  },
  {
    q: "How many credits do I need to generate an animation?",
    a: "A standard generation costs 5 credits. If the generation task fails, the credits will be automatically refunded to your account."
  },
  {
    q: "What if I'm not satisfied with the generated result?",
    a: "AI-generated sequences aren't always perfect on the first try. You can select 'Regenerate' in your dashboard to reload the parameters, adjust your prompt or motion type, and try again."
  },
  {
    q: "Can the generated animations be used in my game projects?",
    a: "Absolutely! Rika AI supports free export of sprite sheets (PNG) and GIFs, which are ready to be imported into any game engine."
  }
];

const LandingPage: React.FC<LandingPageProps> = ({ onGetStarted, onViewDocs }) => {
  const [selectedMotion, setSelectedMotion] = useState<string>('idle');

  const heroImage = useMemo(() => {
    const images = [
      `${CDN_BASE}image1.gif`,
      `${CDN_BASE}image2.gif`,
      `${CDN_BASE}image3.gif`
    ];
    return images[Math.floor(Math.random() * images.length)];
  }, []);

  return (
    <div className="bg-[#0d0221] text-white selection:bg-[#5a2d9c] selection:text-white overflow-hidden font-pixel">
      {/* SECTION 1: HERO */}
      <section className="min-h-[80vh] flex flex-col lg:flex-row items-center justify-center px-6 lg:px-24 gap-12 py-16">
        <div className="flex-1 space-y-6 text-center lg:text-left">
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight uppercase text-[#f7d51d] text-pretty">
            RIKA AI
          </h1>
          <div className="space-y-4">
             <h2 className="text-base md:text-lg font-medium text-white/90 leading-tight uppercase tracking-wider text-pretty">
                make your pixel art to live
             </h2>
             <p className="text-[8px] md:text-[9px] text-white/40 uppercase tracking-[0.15em] leading-relaxed max-w-md mx-auto lg:mx-0 text-pretty">
                The ultimate ai animation toolkit for 2D game developers. Transform static pixel-style character into frame sequences.
                <br /><br />
                Imagination is All you need.
             </p>
          </div>
          <div className="pt-4">
            <PixelButton 
              variant="outline"
              className="w-full max-w-[200px] h-11 text-[10px] hover:translate-y-[-1px] transition-all"
              onClick={onGetStarted}
            >
              GET STARTED
            </PixelButton>
          </div>
        </div>

        <div className="flex-1 flex justify-center items-center w-full max-w-sm lg:max-w-none">
          <div className="w-full aspect-square pixel-border bg-[#2d1b4e]/10 flex items-center justify-center overflow-hidden relative group">
            <div className="absolute inset-0 bg-gradient-to-br from-[#5a2d9c]/5 to-transparent"></div>
            <img 
              src={heroImage} 
              className="w-[70%] h-[70%] object-contain animate-fade-in z-10" 
              style={{ imageRendering: 'pixelated' }}
              alt="Hero Animation Preview"
              onError={(e) => {
                e.currentTarget.src = FALLBACK_IMAGE;
              }}
            />
          </div>
        </div>
      </section>

      {/* SECTION 2: PIPELINE (Automatic Animation Generator) */}
      <section className="min-h-screen flex flex-col justify-center py-24 px-6 lg:px-24 bg-black/10 border-t border-[#5a2d9c]/10">
        <div className="text-center mb-24 space-y-2">
          <h2 className="text-xl md:text-2xl font-bold uppercase tracking-tight text-[#f7d51d] text-pretty">Automatic Animation Generator</h2>
          <p className="text-[8px] text-white/30 uppercase tracking-[0.4em] text-pretty">End-to-End Motion Synthesis Pipeline</p>
        </div>

        <div className="max-w-7xl mx-auto flex flex-col lg:flex-row items-start justify-center gap-12 lg:gap-0 w-full px-4 relative">
          
          {/* STEP 1 */}
          <div className="flex-1 flex flex-col items-center gap-6 w-full relative">
            <div className="text-xl font-bold text-[#5a2d9c]/50">01</div>
            <h3 className="text-[7.5px] md:text-[8px] font-bold uppercase text-white tracking-widest text-center whitespace-nowrap">
              upload pixel character
            </h3>
            
            <div className="w-full max-w-[280px] relative">
              <div className="aspect-square bg-[#1e1e1e]/60 pixel-border border-[#5a2d9c] flex items-center justify-center overflow-hidden">
                <img 
                  src={`${CDN_BASE}origin.png`} 
                  className="w-full h-full object-contain"
                  style={{ imageRendering: 'pixelated' }}
                  alt="Original Pixel Character"
                />
              </div>
              {/* ARROW 1 - Centered in gap between Box 1 and Box 2 */}
              <div className="hidden lg:flex absolute top-1/2 -translate-y-1/2 left-[calc(100%+12px)] z-10">
                <div className="w-0 h-0 border-t-[8px] border-t-transparent border-b-[8px] border-b-transparent border-l-[12px] border-l-[#5a2d9c]/40"></div>
              </div>
            </div>

            <div className="text-white text-[9px] uppercase opacity-40 tracking-[0.3em] h-8 flex items-center">
              64x64
            </div>
          </div>

          {/* STEP 2 */}
          <div className="flex-1 flex flex-col items-center gap-6 w-full relative">
            <div className="text-xl font-bold text-[#5a2d9c]/50">02</div>
            <h3 className="text-[7.5px] md:text-[8px] font-bold uppercase text-white tracking-widest text-center whitespace-nowrap">
              choose motion
            </h3>

            <div className="w-full max-w-[280px] relative">
              <div className="aspect-square flex flex-col justify-center items-center text-center p-4">
                <p className="text-[9px] text-white/50 leading-relaxed break-words italic px-2">
                  "{MOTION_PROMPTS[selectedMotion]}"
                </p>
              </div>
              {/* ARROW 2 - Positioned more to the left (closer to Step 2 box) */}
              <div className="hidden lg:flex absolute top-1/2 -translate-y-1/2 left-[calc(100%+6px)] z-10">
                <div className="w-0 h-0 border-t-[8px] border-t-transparent border-b-[8px] border-b-transparent border-l-[12px] border-l-[#5a2d9c]/40"></div>
              </div>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 w-full max-w-[280px]">
              {MOTION_TYPES.map(motion => (
                <button
                  key={motion}
                  onClick={() => setSelectedMotion(motion)}
                  className={`px-2 py-2 text-[7px] font-bold uppercase transition-all pixel-border border-2 ${
                    selectedMotion === motion 
                    ? 'bg-[#f7d51d] text-[#2d1b4e] border-white' 
                    : 'bg-[#2d1b4e] text-white/60 border-[#5a2d9c] hover:border-white/50'
                  }`}
                >
                  {motion}
                </button>
              ))}
            </div>
          </div>

          {/* STEP 3 */}
          <div className="flex-1 flex flex-col items-center gap-6 w-full relative">
            <div className="text-xl font-bold text-[#5a2d9c]/50">03</div>
            <h3 className="text-[7.5px] md:text-[8px] font-bold uppercase text-white tracking-widest text-center whitespace-nowrap">
              generate animation
            </h3>

            <div className="w-full max-w-[280px]">
              <div 
                className="aspect-square bg-[#1e1e1e] pixel-border border-[#f7d51d] flex items-center justify-center overflow-hidden relative"
                style={{
                  backgroundImage: `conic-gradient(#252525 25%, #1a1a1a 25% 50%, #252525 50% 75%, #1a1a1a 75%)`,
                  backgroundSize: `${100 / 32}% ${100 / 32}%`,
                }}
              >
                <img 
                  src={`${EXAMPLES_BASE}${selectedMotion}_64.gif`} 
                  key={selectedMotion}
                  className="w-full h-full object-contain animate-fade-in relative z-10"
                  style={{ 
                    imageRendering: 'pixelated',
                    mixBlendMode: 'lighten'
                  }}
                  alt={`${selectedMotion} Animation Example`}
                  onError={(e) => {
                    e.currentTarget.src = FALLBACK_IMAGE;
                  }}
                />
              </div>
            </div>

            <div className="w-full max-w-[200px] h-8 flex items-center">
               <PixelButton 
                 variant="primary" 
                 className="w-full h-11 text-[9px] shadow-[0_0_15px_rgba(247,213,29,0.3)]"
                 onClick={onGetStarted}
               >
                 GENERATE
               </PixelButton>
            </div>
          </div>
        </div>

        {/* TUTORIAL VIDEO SECTION */}
        <div className="max-w-4xl mx-auto w-full mt-28 px-4 flex flex-col items-center">
          <div className="mb-6 flex flex-col items-center gap-1">
            <h3 className="text-[10px] md:text-[11px] font-bold uppercase tracking-[0.3em] text-[#f7d51d]">Watch Tutorial</h3>
            <div className="w-12 h-0.5 bg-[#f7d51d] opacity-40"></div>
          </div>
          <div className="pixel-border bg-black/40 overflow-hidden relative pointer-events-none select-none w-full">
            <video 
              src={`${CDN_BASE}tutorial.mp4`} 
              autoPlay 
              loop 
              muted 
              playsInline
              className="w-full h-auto block"
              onContextMenu={(e) => e.preventDefault()}
            />
          </div>
          <div className="mt-8">
            <PixelButton 
              variant="secondary"
              className="px-8 h-12 text-[10px] font-bold"
              onClick={onViewDocs}
            >
              VIEW DOCUMENTATION
            </PixelButton>
          </div>
        </div>
      </section>

      {/* SECTION 3: SPRITE PLAYER */}
      <section className="min-h-[70vh] flex flex-col justify-center py-24 px-6 lg:px-24 bg-[#0d0221]">
        <div className="text-center mb-20 space-y-2">
          <h2 className="text-xl md:text-2xl font-bold uppercase tracking-tight text-[#f7d51d] text-pretty">Sprite Player & Editor</h2>
          <p className="text-[8px] text-white/30 uppercase tracking-[0.4em] text-pretty">Powerful, easy-to-use playback and editing tools</p>
          <p className="pt-4 text-[9px] md:text-[10px] text-white/40 uppercase tracking-[0.2em] max-w-2xl mx-auto text-pretty">
            Advanced features including background removal, pixel-perfect frame editing, and smart export options.
          </p>
        </div>

        <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-6 w-full items-stretch px-4">
          {[
            { title: "Background Removal", img: `${CDN_BASE}bgremove.gif` },
            { title: "Pixel Editing", img: `${CDN_BASE}edit.gif` },
            { title: "Sprite Sheet Export", img: `${CDN_BASE}export.gif` }
          ].map((feature) => (
            <div key={feature.title} className="flex flex-col bg-[#1e1e1e] border-2 border-[#3a3a3a] shadow-[8px_8px_0px_#111] overflow-hidden group">
              <div className="flex items-center justify-between px-4 py-3 bg-[#3a3a3a] border-b-2 border-[#4a4a4a]">
                <span className="text-[10px] font-bold uppercase tracking-wider text-white/90">{feature.title}</span>
                <div className="flex gap-1.5">
                   <div className="w-4 h-4 border border-white/20 flex items-center justify-center cursor-default">
                      <div className="w-2.5 h-[1px] bg-white/40"></div>
                   </div>
                   <div className="w-4 h-4 border border-white/20 flex items-center justify-center cursor-default">
                      <span className="text-[8px] text-white/40 leading-none">×</span>
                   </div>
                </div>
              </div>
              <div className="w-full aspect-[4/3] relative bg-black flex items-center justify-center overflow-hidden">
                 <img 
                   src={feature.img} 
                   className="w-full h-full object-cover group-hover:scale-[1.03] transition-transform duration-700" 
                   style={{ imageRendering: 'pixelated' }} 
                   alt={feature.title}
                   onError={(e) => {
                     e.currentTarget.src = FALLBACK_IMAGE;
                   }}
                 />
                 <div className="absolute inset-0 bg-gradient-to-b from-white/5 via-transparent to-transparent pointer-events-none"></div>
                 <div className="absolute inset-0 opacity-0 group-hover:opacity-10 pointer-events-none transition-opacity bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.25)_50%),linear-gradient(90deg,rgba(255,0,0,0.06),rgba(0,255,0,0.02),rgba(0,0,255,0.06))] bg-[length:100%_2px,3px_100%]"></div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-16 flex justify-center">
          <PixelButton 
            variant="outline"
            className="w-full max-w-[200px] h-12 text-[10px] font-bold hover:bg-[#f7d51d] hover:text-[#0d0221] transition-all"
            onClick={onGetStarted}
          >
            TRY EDITOR
          </PixelButton>
        </div>
      </section>

      {/* SECTION 4: GALLERY */}
      <section className="py-24 bg-black/20 border-t border-[#5a2d9c]/10 relative overflow-hidden">
        <div className="text-center mb-16 space-y-2 px-6">
          <h2 className="text-xl md:text-2xl font-bold uppercase tracking-tight text-[#f7d51d] text-pretty">GALLERY</h2>
          <p className="text-[8px] text-white/30 uppercase tracking-[0.4em] text-pretty">Generated by Rika AI</p>
        </div>

        <div className="relative flex overflow-hidden">
          <div className="flex animate-marquee whitespace-nowrap">
            {[...DISPLAY_GIFS, ...DISPLAY_GIFS].map((src, i) => (
              <div key={i} className="inline-block px-4 py-2">
                <div className="w-[180px] md:w-[220px] aspect-square pixel-border border-[#5a2d9c]/30 bg-[#2d1b4e]/20 flex items-center justify-center p-6 group hover:border-[#f7d51d] transition-all cursor-pointer">
                  <img 
                    src={src} 
                    className="w-full h-full object-contain group-hover:scale-110 transition-transform" 
                    style={{ imageRendering: 'pixelated' }} 
                    alt={`Gallery Display ${i}`}
                    onError={(e) => {
                      e.currentTarget.src = FALLBACK_IMAGE;
                    }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SECTION 5: FAQ */}
      <section className="py-24 px-6 lg:px-24 bg-[#0d0221] border-t border-[#5a2d9c]/10">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16 space-y-2">
            <h2 className="text-xl md:text-2xl font-bold uppercase tracking-tight text-[#f7d51d] text-pretty">Frequently Asked Questions</h2>
            <p className="text-[8px] text-white/30 uppercase tracking-[0.4em] text-pretty">Common Inquiries about Rika AI</p>
          </div>

          <div className="space-y-12">
            {FAQS.map((item, idx) => (
              <div key={idx} className="space-y-4 text-left border-l-2 border-[#5a2d9c]/30 pl-6 hover:border-[#f7d51d] transition-colors">
                <div className="flex items-start gap-4">
                  <span className="text-[#f7d51d] font-bold text-xs shrink-0">Q:</span>
                  <h3 className="text-[10px] md:text-[11px] font-bold uppercase leading-relaxed text-white text-pretty">
                    {item.q}
                  </h3>
                </div>
                <div className="flex items-start gap-4">
                  <span className="text-white/40 font-bold text-xs shrink-0">A:</span>
                  <p className="text-[9px] md:text-[10px] leading-relaxed text-white/60 text-pretty">
                    {item.a}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="pt-24 pb-12 text-center bg-[#0d0221] flex flex-col items-center border-t border-[#5a2d9c]/10">
         <div className="max-w-2xl mx-auto space-y-6 px-6 mb-16">
            <div className="flex flex-col items-center justify-center space-y-2">
              <h3 className="text-lg font-bold uppercase tracking-tight text-white text-pretty">Ready to Animate?</h3>
              <p className="text-[10px] text-white/30 uppercase tracking-[0.3em] text-pretty">Try Rika AI</p>
            </div>
            <div className="pt-4">
              <PixelButton onClick={onGetStarted} variant="outline" className="w-full max-w-[200px] mx-auto h-12 text-[10px] font-bold">
                GET STARTED
              </PixelButton>
            </div>
            <div className="pt-8 opacity-10">
               <p className="text-[7px] uppercase tracking-[0.5em] text-pretty">Rika AI • v1.0.42</p>
            </div>
         </div>

         <div className="w-full max-w-7xl px-8 mt-auto border-t border-white/5 pt-10 flex flex-col md:flex-row justify-between items-center gap-8 md:gap-0 text-[9px] uppercase tracking-widest">
            <div className="text-white/70 font-medium">
              © 2025 Rika AI. All rights reserved.
            </div>
            
            <div className="flex flex-col items-center md:items-end gap-2">
              <span className="text-[8px] uppercase tracking-[0.25em] text-[#f7d51d] font-bold">Contact</span>
              <a 
                href="mailto:amusingyyy@gmail.com" 
                className="flex items-center gap-2.5 text-white/70 hover:text-white transition-all group"
              >
                <span className="font-medium tracking-wide">amusingyyy@gmail.com</span>
                <div className="bg-white/10 p-1.5 rounded-sm group-hover:bg-white/20 transition-colors">
                  <svg className="w-3.5 h-3.5 fill-current" viewBox="0 0 24 24">
                    <path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z"/>
                  </svg>
                </div>
              </a>
            </div>
         </div>
      </footer>

      <style dangerouslySetInnerHTML={{ __html: `
        @keyframes fade-in {
          from { opacity: 0; transform: translateY(4px); }
          to { opacity: 1; transform: translateY(0); }
        }
        @keyframes marquee {
          0% { transform: translateX(0); }
          100% { transform: translateX(-50%); }
        }
        .animate-fade-in {
          animation: fade-in 1.2s cubic-bezier(0.2, 0.8, 0.2, 1) forwards;
        }
        .animate-marquee {
          animation: marquee 40s linear infinite;
        }
        .animate-marquee:hover {
          animation-play-state: paused;
        }
        .text-pretty {
          text-wrap: pretty;
        }
        .font-pixel {
          font-family: 'Press Start 2P', cursive;
          image-rendering: pixelated;
        }
      `}} />
    </div>
  );
};

export default LandingPage;
